export type OptionsType = {
  id?: string,
  className?: string,
  textContent?: string,
  innerText?: string,
  innerHTML?: string,
  value?: string,
  type?: string,
  placeholder?: string,
  href?: string,
  src?: string,
  alt?: string,
  min?: string,
  max?: string,
  maxLength?: string,
  for?: string,
  required?: boolean,
  disabled?: boolean
  rows?: string,
};
